esphome:
  name: electric-fence-monitor
  friendly_name: Electric Fence Monitor
  project:
    name: miestas-art.electric-fence-monitor
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "EFM Fallback Hotspot"
    password: "YOURownPWD8re"

captive_portal:

one_wire:
  - platform: gpio
    pin: GPIO4
    id: one_wire_bus

sensor:
  - platform: internal_temperature
    name: "ESP Prototype A Internal Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"

  - platform: wifi_signal
    name: "ESP Prototype A WiFi Signal dBm"
    unit_of_measurement: "dBm"
    icon: "mdi:wifi"
    id: wifi_signal_dbm    

  - platform: adc
    pin: GPIO34
    name: "Fence Voltage strenght"
    attenuation: 11db
    samples: 255
    sampling_mode: max
    update_interval: 1ms
    filters:
      - max:
          window_size: 1000 
          send_every: 1000
      - calibrate_linear:
          - 0.14 -> 0.0
          - 1.25 -> 100.0
      - round: 1
    unit_of_measurement: "%"
    device_class: power_factor
    state_class: measurement
    accuracy_decimals: 1

  - platform: dallas_temp
#    address: 0x1234567812345628
    name: "External DS18B20 Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    update_interval: 30s
