esphome:
  name: electric-fence-monitor
  friendly_name: Electric Fence Monitor
  project:
    name: miestas-art.electric-fence-monitor
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Improve stability
  power_save_mode: none

# Enable a web server for debugging
web_server:
  port: 80

# --- SENSOR DEFINITIONS ---

# 1-Wire bus for temperature sensors
dallas:
  - pin: GPIO4 # Change to your 1-Wire data pin

# I2C bus for ambient light sensor
i2c:
  sda: GPIO21 # Default ESP32 I2C SDA
  scl: GPIO22 # Default ESP32 I2C SCL
  scan: true

sensor:
  # 1. High-Voltage Sensor
  - platform: adc
    pin: GPIO34 # Change to your ADC pin for voltage sensing
    name: "Fence Voltage"
    id: fence_voltage_raw
    attenuation: 11db
    update_interval: 10s
    filters:
      # The resistor divider is 100MΩ and 20kΩ.
      # Vin = Vout * (R1 + R2) / R2
      # Vin = Vout * (100,000,000 + 20,000) / 20,000
      # Vin = Vout * 5001
      # The result is divided by 1000 to get kV.
      - lambda: return x * 5.001;
    unit_of_measurement: "kV"
    icon: "mdi:transmission-tower"

  # 2. Temperature Sensors (DS18B20)
  - platform: dallas
    address: 0x... # Replace with your first sensor's address
    name: "Air Temperature"
  - platform: dallas
    address: 0x... # Replace with your second sensor's address
    name: "Soil Temperature"
  - platform: dallas
    address: 0x... # Replace with your third sensor's address
    name: "Box Temperature"

  # 3. Rain Sensor
  - platform: adc
    pin: GPIO35 # Change to your ADC pin for the rain sensor
    name: "Rain Level"
    update_interval: 60s
    attenuation: 11db
    icon: "mdi:weather-rainy"
    filters:
      # Invert the value so higher means more rain
      - lambda: return (3.3 - x) / 3.3 * 100.0;
    unit_of_measurement: "%"

  # 4. UV Sensor (GUVA-S12SD)
  - platform: adc
    pin: GPIO32 # Change to your ADC pin for the UV sensor
    name: "UV Index"
    attenuation: 11db
    update_interval: 60s
    icon: "mdi:sun-wireless"
    filters:
      # The GUVA-S12SD outputs a voltage proportional to the UV Index.
      # 1V corresponds to a UV Index of 10.
      # UVI = Vout * 10
      - lambda: return x * 10.0;

  # 5. Soil Moisture Sensor
  - platform: adc
    pin: GPIO33 # Change to your ADC pin for soil moisture
    name: "Soil Moisture"
    update_interval: 60s
    attenuation: 11db
    icon: "mdi:water-percent"
    filters:
      # Calibrate these values for your sensor in dry air and pure water
      - calibrate_linear:
          - 0.0 -> 100.0 # Voltage in air -> 0%
          - 3.3 -> 0.0  # Voltage in water -> 100%
    unit_of_measurement: "%"

  # 6. Ambient Light Sensor (VEML7700)
  - platform: veml7700
    name: "Ambient Light"
    update_interval: 60s